<s>[INST]Based on the following triplets from a knowledge graph, please answer the given question. Please keep the answers as simple as possible and return all the possible answers as a list.

Triplets:
xxx
xxx
xxx
xxx

Question:
xxx?[/INST]xxxx</s>

bos + bos_inst + inst + triplet + query + eos_inst + labels + eos

In [5]:
import torch
# https://github.com/mufeili/LTRoG/tree/dev_mufei/scored_triples
data = torch.load("cwq_240905_val.pth")

In [6]:
type(data)

dict

In [8]:
len(data.keys())

2837

In [9]:
sample = data['WebQTest-823_ed31f9dd431831dbd32a06b958c7c97c']

In [10]:
type(sample)

dict

In [11]:
sample.keys()

dict_keys(['question', 'scored_triples', 'q_entity', 'q_entity_in_graph', 'a_entity', 'a_entity_in_graph', 'max_path_length', 'target_relevant_triples'])

In [12]:
sample['question']

'What country borders Bolivia and contains Goiás?'

In [14]:
sample['q_entity'], sample['q_entity_in_graph']

(['Bolivia', 'Goiás'], ['Bolivia', 'Goiás'])

In [15]:
sample['a_entity'], sample['a_entity_in_graph']

(['Brazil'], ['Brazil'])

In [17]:
len(sample['scored_triples'])  # all triples

4623

In [18]:
sample['scored_triples'][0]

('Mamoré River',
 'geography.river.basin_countries',
 'Brazil',
 0.8839638829231262)

In [19]:
import pickle
with open('samples/cwq_val_org.pkl', 'rb') as f:
    data = pickle.load(f)

In [23]:
for item in data:
    if item['id'] == 'WebQTest-823_ed31f9dd431831dbd32a06b958c7c97c':
        data_item = item

In [28]:
data_item["relation_list"][data_item["r_id_list"][0]]

'base.braziliangovt.politician.phone_contact'

In [30]:
from torch.nn.functional import gumbel_softmax
logits = torch.tensor([0.3, 0.5, 0.9, 3.3])
gumbel_softmax(logits, hard=True)

tensor([0., 0., 0., 1.])

In [32]:
import torch

# 示例张量
tensor = torch.tensor([3, 1, 5, 9, 7])

# 找出前3大值，sorted=False
values, indices = tensor.topk(3, sorted=False)
print(indices)  # 输出: tensor([7, 9, 5])，顺序不固定

# 找出前3大值，sorted=True
values, indices = tensor.topk(3, sorted=True)
print(indices)  # 输出: tensor([9, 7, 5])，按降序排列


tensor([3, 4, 2])
tensor([3, 4, 2])


In [33]:
import torch

In [34]:
logits = torch.tensor([[0.3], [0.5], [2.6], [3.3]])
for i in logits:
    print(i)

tensor([0.3000])
tensor([0.5000])
tensor([2.6000])
tensor([3.3000])
