<s>[INST]Based on the following triplets from a knowledge graph, please answer the given question. Please keep the answers as simple as possible and return all the possible answers as a list.

Triplets:
xxx
xxx
xxx
xxx

Question:
xxx?[/INST]xxxx</s>

bos + bos_inst + inst + triplet + query + eos_inst + labels + eos

In [43]:
import torch
# https://github.com/mufeili/LTRoG/tree/dev_mufei/scored_triples
data = torch.load("./samples/cwq_240905_val.pth")

In [44]:
sample_scored_823 = data['WebQTest-823_ed31f9dd431831dbd32a06b958c7c97c']

In [45]:
import pickle
with open('samples/cwq_val_org.pkl', 'rb') as f:
    data_org = pickle.load(f)

In [46]:
for item in data_org:
    if item['id'] == 'WebQTest-823_ed31f9dd431831dbd32a06b958c7c97c':
        data_item = item

In [53]:
fh_id_list, fr_id_list, ft_id_list = [], [], []

# TODO: check `scored_triplets` is pre-sorted.
scored_triplets = sample_scored_823['scored_triples']
assert len(scored_triplets) == len(data_item["h_id_list"])
filtered_triplets = [(t[0], t[1], t[2]) for idx, t in enumerate(scored_triplets) if idx < 500]
# print(filtered_triplets)
# TODO: check if it is correct.
entity_list = data_item['text_entity_list'] + data_item['non_text_entity_list']
relation_list = data_item['relation_list']

for h_id, r_id, t_id in zip(data_item['h_id_list'], data_item['r_id_list'], data_item['t_id_list']):
    h, r, t = entity_list[h_id], relation_list[r_id], entity_list[t_id]
    if (h,r,t) in filtered_triplets:
        fh_id_list.append(h)
        fr_id_list.append(r)
        ft_id_list.append(t)

len(fh_id_list), len(fr_id_list), len(ft_id_list)

(500, 500, 500)

In [30]:
from torch.nn.functional import gumbel_softmax
logits = torch.tensor([0.3, 0.5, 0.9, 3.3])
gumbel_softmax(logits, hard=True)

tensor([0., 0., 0., 1.])

In [32]:
import torch

# 示例张量
tensor = torch.tensor([3, 1, 5, 9, 7])

# 找出前3大值，sorted=False
values, indices = tensor.topk(3, sorted=False)
print(indices)  # 输出: tensor([7, 9, 5])，顺序不固定

# 找出前3大值，sorted=True
values, indices = tensor.topk(3, sorted=True)
print(indices)  # 输出: tensor([9, 7, 5])，按降序排列


tensor([3, 4, 2])
tensor([3, 4, 2])


In [1]:
import torch

In [7]:
data = torch.load("./samples/gpt_labeled_webqsp_cleaned.pt")
[key  for i,key in enumerate(data.keys()) if i > 1000]

['WebQTest-1264',
 'WebQTest-1265',
 'WebQTest-1266',
 'WebQTest-1267',
 'WebQTest-1268',
 'WebQTest-1269',
 'WebQTest-1270',
 'WebQTest-1271',
 'WebQTest-1272',
 'WebQTest-1274',
 'WebQTest-1275',
 'WebQTest-1276',
 'WebQTest-1277',
 'WebQTest-1278',
 'WebQTest-1279',
 'WebQTest-1280',
 'WebQTest-1281',
 'WebQTest-1282',
 'WebQTest-1284',
 'WebQTest-1285',
 'WebQTest-1287',
 'WebQTest-1289',
 'WebQTest-1291',
 'WebQTest-1292',
 'WebQTest-1293',
 'WebQTest-1294',
 'WebQTest-1295',
 'WebQTest-1296',
 'WebQTest-1297',
 'WebQTest-1298',
 'WebQTest-1300',
 'WebQTest-1301',
 'WebQTest-1303',
 'WebQTest-1304',
 'WebQTest-1305',
 'WebQTest-1306',
 'WebQTest-1307',
 'WebQTest-1308',
 'WebQTest-1309',
 'WebQTest-1310',
 'WebQTest-1311',
 'WebQTest-1312',
 'WebQTest-1313',
 'WebQTest-1314',
 'WebQTest-1316',
 'WebQTest-1317',
 'WebQTest-1319',
 'WebQTest-1320',
 'WebQTest-1321',
 'WebQTest-1322',
 'WebQTest-1323',
 'WebQTest-1324',
 'WebQTest-1325',
 'WebQTest-1326',
 'WebQTest-1327',
 'WebQTest

In [44]:
len(data)

1628

In [46]:
type(data)

dict

In [3]:
data["WebQTest-823"]

[('Bolivia', 'location.location.adjoin_s', 'm.059020c'),
 ('Bolivia', 'location.location.adjoin_s', 'm.03yvv83'),
 ('Bolivia', 'location.location.adjoin_s', 'm.0590206'),
 ('Bolivia', 'location.location.adjoin_s', 'm.059020j'),
 ('Bolivia', 'location.location.adjoin_s', 'm.02ws93m'),
 ('m.059020j', 'location.adjoining_relationship.adjoins', 'Argentina'),
 ('m.03yvv83', 'location.adjoining_relationship.adjoins', 'Peru'),
 ('m.0590206', 'location.adjoining_relationship.adjoins', 'Chile'),
 ('m.059020c', 'location.adjoining_relationship.adjoins', 'Paraguay'),
 ('m.02ws93m', 'location.adjoining_relationship.adjoins', 'Brazil')]

In [50]:
import torch.nn.functional as F
F.one_hot(torch.tensor([0,0,0,1,1,1,0]).long(), num_classes=2)

tensor([[1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0]])

In [13]:
import pickle
processed_file = f'./samples/cwq_val_org.pkl'
with open(processed_file, 'rb') as f:
    data = pickle.load(f)
data[2]["question"]

'What country borders Bolivia and contains Goiás?'

In [14]:
embs = torch.load("./samples/14.pth")

In [31]:
[dat for i, dat in enumerate(embs.keys()) if i< 20]

['WebQTrn-470_a7a3deb793f57da6521519210692d07b',
 'WebQTrn-659_c32736bc2120c8c423e1f9825b03fb9d',
 'WebQTrn-3529_ab1f7e79e43f8a9ffeb41c4a7958ba1a',
 'WebQTrn-3529_55548390bd42e860db5a4eaa47f41933',
 'WebQTrn-1816_d924c0e2ecd8ee8289e86c845eff324b',
 'WebQTrn-3708_01a4413d660ce6c167d24902308c371f',
 'WebQTrn-2095_d0b7ab9295b2c339d2bc24073e8b989d',
 'WebQTest-937_9c30227e437d561a395bf8370530b6e6',
 'WebQTrn-1529_17dce559f069bbd76f045192423e1ce0',
 'WebQTrn-191_58b0250f2733b0900ac799b2313c8e11',
 'WebQTrn-1784_64171540ebbcc9d1f823c1963cb718e1',
 'WebQTrn-1418_783334c8ae46f986277cf8626256e0b6',
 'WebQTrn-538_7835fa0c9d5a5be03696300d3a289b68',
 'WebQTest-723_765aa77e645df9635fc02a6bd7266e1a',
 'WebQTrn-3012_3c285fca47050d6180e517efcdcb892c',
 'WebQTrn-2686_c3e4efd051fa3ee9af31e20cfa735f1c',
 'WebQTrn-1625_1bc85cf9eab0a0714557180ac27e91a2',
 'WebQTrn-1066_4c3cb42d0c0b43866b7fb51c0c9c630d',
 'WebQTrn-191_20914e3aca9d189989fc61a5be6f7e83',
 'WebQTrn-314_7307101cc5def332a7d6ec9b44c2b45b']

In [18]:
emb = embs['WebQTest-937_9c30227e437d561a395bf8370530b6e6']
emb['entity_embs'].shape, emb['q_emb'].shape, emb['relation_embs'].shape,
# emb['entity_embs'].shape[0] == len(data_target['text_entity_list'])
# emb['relation_embs'].shape[0] == len(data_target['relation_list'])

(torch.Size([510, 1024]), torch.Size([1, 1024]), torch.Size([168, 1024]))

In [37]:
processed_file = f'./samples/cwq_val_org.pkl'
with open(processed_file, 'rb') as f:
    data = pickle.load(f)
for dat in data:
    if dat['id'] == 'WebQTest-823_ed31f9dd431831dbd32a06b958c7c97c':
        data_target = dat

In [38]:
len(data_target['h_id_list'])

4623

In [25]:
data_target['relation_list'][:5]

['base.aareas.administrative_area_level.examples',
 'base.aareas.schema.administrative_area.administrative_area_type',
 'base.aareas.schema.administrative_area.administrative_children',
 'base.aareas.schema.administrative_area.administrative_parent',
 'base.aareas.schema.administrative_area.pertinent_type']

In [26]:
data_target['text_entity_list'][:5]

['1929 Palestine riots',
 '1936–39 Arab revolt in Palestine',
 '1947–1948 Civil War in Mandatory Palestine',
 '1948 Arab–Israeli War',
 '1948 Palestine war']

In [27]:
data_target['non_text_entity_list'][:5]

['g.11x7vs_wz', 'g.1210xv5p', 'g.12182mtl', 'g.121r_c5j', 'g.1223dz43']

In [28]:
data_target['h_id_list'][:4]

[41, 245, 131, 270]

In [30]:
processed_file = f'./samples/cwq_val_org.pkl'
with open(processed_file, 'rb') as f:
    data = pickle.load(f)
[dat['id'] for i, dat in enumerate(data) if i< 20]

['WebQTrn-1430_ac053cda0a7424c48e4809c71171fbed',
 'WebQTrn-2505_eba9c2e29a1198e8b56c2f7e4210638b',
 'WebQTest-823_ed31f9dd431831dbd32a06b958c7c97c',
 'WebQTrn-2181_8d86dc5e03446f0e50fd69bc06ae0658',
 'WebQTrn-1447_f1ea2e60c0bd4311ef47cc0d7f6c0dd8',
 'WebQTrn-453_2326103f221042f024262b19814ee9d3',
 'WebQTrn-453_8c50e30ac5163e6dabfc999a7129a4ea',
 'WebQTrn-1929_de8581ad379fdf8fb0e03c89e19ead1a',
 'WebQTrn-970_33a7e145f293d98099b1cd924ec3378f',
 'WebQTrn-1948_f2ac0ed793fc82b685d4c71e78a53a59',
 'WebQTest-1081_6118bd42202be020c123831a76c283c6',
 'WebQTrn-3287_ebfe3c418f7914f9babf21caade27b05',
 'WebQTrn-2873_143c89d70679c3e5257c93d8e2bc4c67',
 'WebQTest-1508_872253e47dd6ddaa213ff31eeda8783b',
 'WebQTrn-2674_831fb3325644a924d433e2b267f6d238',
 'WebQTrn-860_02bcf2def8fd43213ec01b3c1396b6b9',
 'WebQTrn-2505_ac82b6d5645072d4ce73abb6e57a55d5',
 'WebQTest-811_22a085e4a873315a9c2e63361cbd9248',
 'WebQTrn-2631_770d8b533fd2f564cf8401e6727b03f6',
 'WebQTest-1638_85f381b8012b4def553954906bc9fafb']

In [41]:
("a", "b", "c") in [("a", "b", "c")]

False